### ISSUE TITLE
Cant open some scenes because of error SPK

### ISSUE THREAD

**Issue by Aztec2012** [AdrienTD/c47edit#8]
Cant open some scenes because of error SPK. Its C5-2_The_End.zip, C5_1_Elevators.zip, Guard_Call_Professor.zip, IngameDisplayItems.zip, LapTopMain.zip.

![c47editerrorspk](https://github.com/AdrienTD/c47edit/assets/12844419/a697e304-cedd-440f-b412-a9cfda5a9b2a)

**Comment by AdrienTD** [comment]
If the Zip file doesn't contain the file Pack.SPK, then it is not a scene, so you cannot open it.

In fact, if you take a look at the zip, you will see that it only contains font files and perhaps some facial animations.

Not an issue, closed.
